usethis::use_pipe()
usethis::use_package( "dplyr" )
usethis::use_package( "echarts4r" )
usethis::use_package( "magrittr" )
usethis::use_package( "methods" )
usethis::use_package( "DOSE" )
usethis::use_mit_license()
